baseURL = "https://hugo.iwindoors.com/"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# theme
# 主题
theme = "./"
# themes directory
# 主题目录
themesDir = "themes/stack"

# website title
# 网站标题
title = "iwindoors插件集"

